apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    enviroment: dev
  annotations:
    description: "this is a test pod running Nginx"
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
volumes:
  - name: html
    hostPath:
      path: /home/vejkeee/my-first-repo/index.html
